[simulation]
n_steps = 200
n_print = 1
n_flush = 1
time_step = 0.02
respa_inner = 5
cancel_com_momentum = true

# electrostatics
dielectric_const = 15.0     
coulombtype = 'PIC_Spectral'

# temperature
start_temperature = 323
target_temperature = 323
tau = 0.1
thermostat_coupling_groups = []

# pressure
# pressure = true               # Uncomment in HyMD
# barostat_type = 'berendsen'   #
# barostat = 'semiisotropic'    #
barostat = 'berendsen'          # Comment in HyMD
barostat_type = 'semiisotropic' #
tau_p = 0.1
target_pressure = [1.0, 1.0]

[field]
mesh_size = [20, 20, 40]
kappa = 0.05
sigma = 0.5
rho0 = 8.86
a = 9.21
chi = [
    # ['A','A', 0.0] => No need to specify self-interactions, assumed to be 0.0
]

[nn]
n_epochs = 1000
equilibration = 2000
teacher_forcing = false
chain = false

[nn.optimizer] 
name = 'adam'
learning_rate = 0.1
b1 = 0.1
b2 = 0.4

[nn.loss]
name = 'density_and_apl'
metric = "mse"
com_type = "C1"
target_density = "../reference_aa.npy"
n_lipids = 80
width_ratio = 0.5
target_apl = 0.64
apl_weight = 100  # implies apl in angstrom
  
[nn.model]
chi = true
self_interaction = false
